server:
  port: 44000
spring:
  application:
    name: test-producer
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtualHost: /
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 3
        prefetch: 3
logging:
  level:
    org.springframework.boot.autoconfigure: error
